### ISSUE TITLE
The /sml-lib/Makefile do not work with the newest version of MLton

### ISSUE THREAD

**Issue by Neuromancer42** [IntelLabs/flrc#2]
I tried to build flrc with **MLton 20130715**, but it failed at first, shows `Error: /home/neuromancer/Projects/FLRC/flrc/sml-lib/mlton/basic/sources.mlb 15.7.`

I found this in the Line 3 of /sml-lib/Makefile, which writes:
`MLTON_LIBDIR=$(abspath $(dir $(MLTON_BIN))/../lib/mlton/sml)`

But when I check the actual structure in my local MLton directory structure, I think it should be: `MLTON_LIBDIR=$(abspath $(dir $(MLTON_BIN))/../lib/sml)`.

The change worked and I build it successfully after this.

**Comment by ninegua** [comment]
Which distro are you using? For me, both older mlton and mlton 20130715 installs to the following directory structure (on 3 different distros, Debian, Redhat, NixOS):

```
${PREFIX}/bin
$(PREFIX)/lib/mlton/
$(PREFIX)/share/man/man1/
```

So changing it to `lib/sml` would certainly break things.

**Comment by ninegua** [comment]
Maybe this is a better way to get the lib directory:

```
mlton -verbose 2|grep 'lib dir'
```

It prints `lib dir: /usr/lib/mlton` on my Debian. What is the output you get?

**Comment by Neuromancer42** [comment]
It's `/home/neuromancer/Applications/mlton/lib`.

**Comment by Neuromancer42** [comment]
Oh, I see... It's because I am using mlton without installation... That's my fault

**Comment by ninegua** [comment]
Ok, no problem.
