### ISSUE TITLE
Targeting MIL

### ISSUE THREAD

**Issue by csabahruska** [IntelLabs/flrc#8]
Is there a documentation about MIL syntax?
What would be the best source of information if I'd like to generate MIL from my own compiler?

**Comment by ninegua** [comment]
I'm afraid the best way to interface with MIL is to import its related module and write code directly emitting MIL IR. Only example I can point you to is the translation from our internal Haskell IR to MIL IR https://github.com/IntelLabs/flrc/blob/master/compiler/as-to-mil/to-mil.sml

**Comment by csabahruska** [comment]
My plan is to pretty print some MIL IR example using the `-print ANormStrictToMil` option. Then study the syntax and the MIL parser and write some simple examples manually.
